### ISSUE TITLE
Detecting sensitive attributes using word vectors

### ISSUE THREAD

**Issue by Hilly12** [synthesized-io/fairlens#37]
Deep search currently uses the Ratcliffe-Obershelp algorithm to match strings in a column with potential aliases to determine whether the attribute corresponds to a sensitive attribute. Using word vectors will remove the need to match with aliases and might be faster.

**Comment by Hilly12** [comment]
I think deep search works pretty well at the moment so might be worth closing this. Configs also offer room for customisation and a language model seems unnecessary.

**Comment by simonhkswan** [comment]
We can consider reopening this if we encounter more issues with sensitive attribute detection hey.
