### ISSUE TITLE
Add "open in colab" badge

### ISSUE THREAD

**Issue by rob-tay** [synthesized-io/fairlens#94]
**Is your feature request related to a problem? Please describe.**
We should have a badge that links to colab. Either to the SDK notebook (when fairlens is added) or to the notebook in this repo)

See here:
https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by simonhkswan** [comment]
Yeah agreed! Lets link it to synthesized-io/notebooks main notebook once we've added fairlens to it
